# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Devin Mui'
tagline:          'A random blog about programming'
description:      'Just a simple high school student interested in programming'
url:              http://devinmui.xyz/blog
baseurl:          /blog/

author:
  name:           'Devin Mui'
  url:            https://www.github.com/devinmui

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/devinmui/blog
